from .load_definition import load_lrpc_def_from_url as load_lrpc_def_from_url
from .load_definition import load_lrpc_def_from_str as load_lrpc_def_from_str
from .load_definition import load_lrpc_def_from_dict as load_lrpc_def_from_dict
from .load_definition import load_lrpc_def_from_file as load_lrpc_def_from_file
