from typing import Protocol, Any


class LrpcTransport(Protocol):
    def __init__(self, **kwargs: Any) -> None: ...

    def read(self, count: int) -> bytes: ...
    def write(self, data: bytes) -> None: ...
