dirs:
    - docs
    - changes
files:
    # TODO: #248 TZ: Enable checking of README.md
    # - README.md
    - CHANGES.md
ignorePatterns:
    # Apparently cppreference block link checking tools
    - pattern: "^https://en.cppreference.com"
