name: Linting
on: [pull_request] # yamllint disable-line rule:truthy
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Reviewdog:
    name: Reviewdog
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write # for posting review comments
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install requirements
        run: |
          pip install -r requirements/dev.txt
          pip install -r requirements/package.txt
      - name: Linkspector
        uses: umbrelladocs/action-linkspector@15f97e56ba84c3f637f2b35035c159c871ae6bb3 # v1.5.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: any
          fail_on_error: true
          config_file: .github/config/.linkspector.yml
      - name: Ruff
        uses: benny123tw/action-ruff@226d241bdf7205e6e048f1407d21bd69a64b7298
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          fail_level: any
          changed_files: false
      - name: MyPy
        uses: tsuyoshicho/action-mypy@c3615998c006f1dee3b5c6f7ec99edace2575687 # v5.1.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          fail_on_error: true
      - name: PyLint
        uses: dciborow/action-pylint@cf6c9bcd79e4aa70e2fbeaf6332d741eb1e0bff8 # v0.1.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          glob_pattern: src
          fail_on_error: true
      - name: yamllint
        uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1.22.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: any
      - name: markdownlint
        uses: reviewdog/action-markdownlint@844fd04b127b0d78328653f182d32988ad41d3d7 # v0.27.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: any
          markdownlint_flags: ". -i external -i changes -i examples/stm32_nucleo_l496/**/License.md"
      - name: towncrier
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: tzijnge/action-towncrier@c946b056364a654eb012caec5b547239abfba01d # v0.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: any
          compare_with: "origin/${{ github.base_ref }}"
      - name: clang-format
        uses: tzijnge/action-clang-format@64f6e73f941942db7f56ce1f98ce671d0d0297b9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: any
          exclude: cmake_build
          clang_format_version: 22
      - name: github-actions-lint
        uses: ne-sachirou/lint-gha-reviewdog@21e9e3be880468f3fceff09b97e02094eb000a43 # v0.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
      - name: languagetool
        uses: reviewdog/action-languagetool@ea19c757470ce0dbfcbc34aec090317cef1ff0b5 # v1.23.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: info
          language: en-US
          patterns: "README.md CHANGES.md docs/**/*.md docs/**/*.txt changes/**/*.md changes/**/*.txt"
          disabled_rules: ""
          disabled_categories: ""
